# Workflow
# Should have name 
name: Hello 

# On tells when the workflow should run (Give indendation by tab)
on:
  workflow_dispatch:
  
# Job tells what the workflow should do there can be one or more than one jobs, hence we write jobs
# job is an object so needs indentation 

jobs:
  # Ist job have indentation
  say-hello:
  # Creates an Ephemeral Container with Ubuntu running 
    runs-on: ubuntu-latest
    # that ephemeral container will have steps to execute , hence name those steps and use run: run has the command 
    steps:
      - name: Say hello to all
        run: echo "Hello Dosto"


